name: noti
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  slide_digital_clock: ^1.0.3
  intl: ^0.19.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.8
  sliding_up_panel: ^2.0.0+1
  analog_clock: ^0.1.1
  timezone: ^0.9.2
  awesome_notifications: ^0.9.2
  flutter_simple_treeview: ^3.0.2
  flutter_native_splash: ^2.2.16
  flutter_svg: ^2.0.9

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter_native_splash:
  color: "#ffffff"
  image: "assets/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/svg/
    - assets/
